spring.application.name=trip-management-service
spring.config.import=optional:configserver:http://localhost:8888

# Variables qui seront récupérées depuis Git
server.port=${trip-management-service.uriport}
spring.datasource.url=${trip-management-service.datasource.url}
spring.datasource.username=${trip-management-service.datasource.username}
spring.datasource.password=${trip-management-service.datasource.password}
spring.jpa.hibernate.ddl-auto=${trip-management-service.jpa.hibernate.ddl-auto}
spring.jpa.show-sql=${trip-management-service.jpa.showsql}


eureka.client.service-url.defaultZone=${trip-management-service.urlregistry}